export const USER_SET = 'USER_SET';
export const USER_SET_PWAS = 'USER_SET_PWAS';
export const USER_DELETE = 'USER_DELETE';
export const USER_TOGGLE_IS_LOADING = 'USER_TOGGLE_IS_LOADING';
export const USER_SET_ERROR = 'USER_SET_ERROR';
export const USER_SET_PWA_FORM = 'USER_SET_PWA_FORM';
