export const ROOT = '/';
export const SETTINGS = '/settings';
export const SETTINGS_USER_PWAS = `${SETTINGS}/pwas`;
export const SETTINGS_USER_FAVORITE_PWAS = `${SETTINGS}/favorites`;
export const SETTINGS_USER_ACCOUNT = `${SETTINGS}/account`;
export const HOME = '/home';
export const PWA_DETAIL = '/pwas/:pwaId';
export const GetPwaDetailUrl = (id) => PWA_DETAIL.replace(':pwaId', id);
export const PWA_TAG_FILTER = '/pwas:pwaTag?';
export const GetPwaTagDetailUrl = (tag) => PWA_TAG_FILTER.replace(':pwaTag?', `?tagName=${tag}`);
export const LOGIN = '/login';
export const REGISTER = '/register';
