export const APP_SET_VERSION = 'APP_SET_VERSION';
export const APP_TOGGLE_NAV_BAR = 'APP_TOGGLE_NAV_BAR';
export const APP_SET_SERVICE_WORKER_REGISTERATION = 'APP_SET_SERVICE_WORKER_REGISTERATION';
export const APP_SET_ADD_TO_HOME_SCREEN_PROMPT = 'APP_SET_ADD_TO_HOME_SCREEN_PROMPT';
export const APP_PUSH_ALERT = 'APP_PUSH_ALERT';
export const APP_DELETE_ALERT = 'APP_DELETE_ALERT';
