export const PWAS_TOGGLE_IS_LOADING = 'PWAS_TOGGLE_IS_LOADING';
export const PWAS_SET = 'PWAS_SET';
export const PWAS_SET_TAGS = 'PWAS_SET_TAGS';
export const PWAS_SET_SEARCH = 'PWAS_SET_SEARCH';
export const PWAS_SET_SEARCH_DATA = 'PWAS_SET_SEARCH_DATA';
export const PWAS_MERGE_FILTER = 'PWAS_MERGE_FILTER';
